### PR TITLE
adding get_by_shortened_id to db driver and dal layer

### PR DESCRIPTION
**Pull request by shabazpatel**

### CODE REVIEW

**Comment by pennyfx** [comment]
This is not a proper regex query.   You can end up with partial matches.  Please add a regex with a string start operator.   When you find more than one item, it throws EntityNotFound,  which is not correct.   What is the minimum length of the ID?  Can I pass in a single letter?

**Comment by shabazpatel** [comment]
Sure, I will add in operator similar to what's used in mongodb
```
db.products.find( { description: { $regex: /^S/, $options: 'm' } } )
```
https://docs.mongodb.com/manual/reference/operator/query/regex/#regex-multiline-match

**Comment by pennyfx** [comment]
Odds of hash duplication with 7 chars.

https://github.com/source-foundry/font-v/issues/2

Linus recommends 10.
https://lkml.org/lkml/2010/10/28/264

I've noticed that with docker I can use 2-3 characters 
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
6026276eddd0        mongo               "docker-entrypoint.s…"   13 days ago         Up 13 days          0.0.0.0:27017->27017/tcp                               mongo
432b6a62b6ff        traefik             "/traefik"               6 weeks ago         Up 6 weeks          80/tcp, 0.0.0.0:80->7777/tcp, 0.0.0.0:8080->8081/tcp   happy_roentgen
f34a4e454772        redis               "docker-entrypoint.s…"   11 months ago       Up 6 weeks          0.0.0.0:6379->6379/tcp                                 redis
$ docker restart 6
Error response from daemon: Multiple IDs found with provided prefix: 6124528468f54d2b65be1a9abf61b1d46cdbbd836ca4564f7948427218d2059d
$ docker restart 62
Error response from daemon: Multiple IDs found with provided prefix: 626fe0f6d0e0b864c65aca7244ababb0a9e01ed67be7922eb71863cb9d8cd83d
$ docker restart 60
60
```

**Comment by shabazpatel** [comment]
@pennyfx That's a nice find. If user provides single character then we can provide similar error as docker does,
```
error: multiple IDs found with provided prefix: <id>
```

**Comment by shabazpatel** [comment]
need to add usage of shortened ids, in cli, sdk and controller

**Pull request merged**
